### ISSUE TITLE
sign in doesn't work

### ISSUE THREAD

**Issue by Artm1ss** [arnavs-0/PocDoc-Public#1]
**Describe the bug**
after creating and downloading my google- sevices.jason and put it in specific folders in the project, after installing app on the emulator I couldn't pass the register or sign with google account. 

**Expected behavior**
please guide me how to pass this step or how could i remove firebase from the project to reach the main activity.

**Desktop (please complete the following information):**
 - OS: windows 10 64
 - ide [android studio]
 - Version [4.1.1]

**Comment by arnavs-0** [comment]
Hi, Thank you for your interest in PocDoc. 

I can't seem to replicate your issue, would you mind if you forked the project so I can take a look at your changes besides the google-services.json?

The authentication will be needed for the other features in the app so it would be best if you kept the authentication part.

Also, check the updated documentation

**Comment by Artm1ss** [comment]
hey, Thank you for your fast respond.
i searched to build my own app.
best regards
